### ISSUE TITLE
API Explorer templates not included in PyPI package

### ISSUE THREAD

**Issue by lnewson** [Cornices/cornice.ext.swagger#87]
When downloading the packaged version of cornice-swagger 0.6.0 from PyPI (which is the latest atm) it's missing the new API explorer templates added in PR https://github.com/Cornices/cornice.ext.swagger/pull/79, meaning that you're unable to use the new `cornice_enable_openapi_explorer` directive, as attempting to use it fails with the following error:
```
[Errno 2] No such file or directory: '/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/cornice_swagger/templates/index.html'
Traceback (most recent call last):
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/cornice_swagger/views.py", line 36, in swagger_ui_template_view
    'cornice_swagger', 'templates/index.html').decode('utf8')
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1149, in resource_string
    self, resource_name
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1393, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lnewson/.virtualenvs/app/lib/python3.6/site-packages/cornice_swagger/templates/index.html'
```

**Comment by gabisurita** [comment]
Thanks for the report! It's probably a MANIFEST issue.
